- name: WandbCallback
  configs:
    project: psf-automatic-icd-10
    entity: null
- name: SaveBestModelCallback
  configs:
    split: val
    target: all
    metric: precision@8
- name: EarlyStoppingCallback
  configs:
    split: val
    target: all
    metric: precision@8
    patience: 10