- name: WandbCallback
  configs:
    project: psf-automatic-icd-10
    entity: null
    # dir: /data/je
- name: SaveBestModelCallback
  configs:
    split: val
    target: all
    metric: map
- name: EarlyStoppingCallback
  configs:
    split: val
    target: all
    metric: map
    patience: 6

